exists("main.png")
exists("icon.png")
click("menu_btn_game.png")
exists("menu_game.png")
click("menu_btn_new.png")
exists("gamemode1_btns.png")
click("menu_btn_game.png")
exists("menu_game.png")
click("menu_btn_abort.png")
exists("abort_game_dialog.png")
click("abort_game_btn.png")
exists("main.png")
click("main_btn_new.png")
exists("gamemode1_btns.png")
//play gamemode und finish